# 监控项设置
monitor:
  # 采集间隔, 单位min
  interval: 1
  hosts: "127.0.0.1:1099"
  rules:
    pattern: ".*"

# 展示项设置
show:
  openUrl: false
  url: "127.0.0.1"
  initPort: 23333

kafka:
  bootstrapServers: "127.0.0.1:9092"
  topic: "topic"

